### ISSUE TITLE
Maybe it would be nice to add credits to the manual pages using apogee.png

### ISSUE THREAD

**Issue by mankeli** [cobbpg/nuflix-studio#1]
Mostly because I'd like to find the original :P, but also would be nice to credit the artist!

**Comment by cobbpg** [comment]
I didn't even know where it came from! I encountered the original via Twitter a while ago through a post that disappeared since then. After some investigation prompted by your request, I found a reference to it [in a video](https://www.youtube.com/watch?v=Hgnslzq1kug&t=285) where it was attributed to [The Pixel Apothecary](https://twitter.com/pixelapothecary). I can't see it anywhere on their Twitter feed, so I attached it here for your pleasure.

![pixel-apothecary-apogee](https://github.com/user-attachments/assets/215f8fff-133b-481f-833c-514264c7bbfb)
